### ISSUE TITLE
```checkL1Bridge``` function does not fetch the correct data

### ISSUE THREAD

**Issue by mehdi-defiesta** [tokamak-network/ton-staking-v2#18]
**Describe the bug**
```checkL1Bridge``` function from ```Layer2ManagerV1_1``` does not fetch the correct l2Ton address from the systemConfig

Here is the code snippet 

```Solidity
    function checkL1Bridge(address _systemConfig)
        public
        view
        returns (bool result, address l1Bridge, address portal, address l2Ton)
    {
        uint8 _type = IL2Register(l2Register).systemConfigType(_systemConfig);

        try ISystemConfig(_systemConfig).l1StandardBridge() returns (address l1Bridge_) {
            if (l1Bridge_ != address(0)) {
                // @audit isn't the inverse ? _type == 1 => optimism legacy and _type == 2 => optimism bedrock
            @>  if (_type == 1) l2Ton = ISystemConfig(_systemConfig).l2Ton();
            @>  else if (_type == 2) l2Ton = LEGACY_ERC20_NATIVE_TOKEN;
                
                // @audit l2 address != 0 does mean that the layer2 is available ?
                if (l2Ton != address(0)) {
                    // if (_type == 1 || _type == 2) {
                    result = true;
                    l1Bridge = l1Bridge_;
                    // }
                }
            }
        //@audit does not return anything if there is no L1Bridge
        } catch (bytes memory) {}

        if (l2Ton == LEGACY_ERC20_NATIVE_TOKEN) {
            try ISystemConfig(_systemConfig).optimismPortal() returns (address portal_) {
                portal = portal_;
            } catch (bytes memory) {
                result = false;
            }
        }
    }
```

The function reads the following storage variable :
```Solidity
    /// systemConfig - type (0:empty, 1: optimism legacy, 2: optimism bedrock native TON)
    mapping (address => uint8) public systemConfigType;
```

**Configuration**
- Severity: Medium

**Impact**
 ```withdrawAndDepositL2```function  will either revert when the function tries to get portal address while sending to Titan. In the other hand, the function might send the wrong amount of gas while depositing on L2. Titan needs a Gas limit required to complete the deposit on L2 while Thanos needs a minimum. gas limit to deposit message on L2. Morever, funds would be sent to the wrong L2.
Here is the code snippet showing that the function ```checkL1Bridge```is called to get the L2Ton address before calling ```depositERC20To``` function. 

```Solidity
    (bool success, bytes memory data) = operator.call(abi.encode(SELECTOR_CHECK_L1_BRIDGE));
    if (!success) revert CheckL1BridgeError(1);

    // require(success, 'false checkL1Bridge')
@> (bool result, address l1Bridge, address portal, address l2Ton) = abi.decode(data, (bool,address,address,address));
    if (!result) revert CheckL1BridgeError(2);
    if (l1Bridge == address(0)) revert CheckL1BridgeError(3);

    uint32 _minDepositGasLimit = 0;
    if (l2Ton != LEGACY_ERC20_NATIVE_TOKEN) _minDepositGasLimit = 210000; // minDepositGasLimit check
@> else if (portal == address(0)) revert CheckL1BridgeError(4);
```

**Recommendation**
```Solidity
function checkL1Bridge(address _systemConfig)
        public
        view
        returns (bool result, address l1Bridge, address portal, address l2Ton)
    {
        uint8 _type = IL2Register(l2Register).systemConfigType(_systemConfig);

        try ISystemConfig(_systemConfig).l1StandardBridge() returns (address l1Bridge_) {
            if (l1Bridge_ != address(0)) {
                if (_type == 1) l2Ton = LEGACY_ERC20_NATIVE_TOKEN;
                else if (_type == 2) l2Ton = ISystemConfig(_systemConfig).l2Ton();

                if (l2Ton != address(0)) {
                    // if (_type == 1 || _type == 2) {
                    result = true;
                    l1Bridge = l1Bridge_;
                    // }
                }
            }
        } catch (bytes memory) {}

        if (l2Ton == LEGACY_ERC20_NATIVE_TOKEN) {
            try ISystemConfig(_systemConfig).optimismPortal() returns (address portal_) {
                portal = portal_;
            } catch (bytes memory) {
                result = false;
            }
        }
    }
```

**Comment by mehdi-defiesta** [comment]
We got the following constant corresponding to the native erc20 token on Titan.
```Solidity
address internal constant LEGACY_ERC20_NATIVE_TOKEN = 0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000;
```
Source: https://explorer.titan.tokamak.network/address/0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000/contracts#address-tabs

**Comment by Zena-park** [comment]
In the contract description document 
https://github.com/tokamak-network/ton-staking-v2/blob/codeReview/docs/en/ton-staking-v2.md#ton-stake-v2-contracts
![스크린샷 2024-06-29 오후 10 02 12](https://github.com/tokamak-network/ton-staking-v2/assets/75723511/2abfb747-d85c-4733-a83e-c6c1d7c0d72e)

For the legacy version witth _type == 1 (Titan is this type.), we create  the [LegacySystemConfig](https://github.com/tokamak-network/ton-staking-v2/blob/codeReview/contracts/layer2/LegacySystemConfig.sol). The l2Ton() function exists in the LegacySystemConfig contract. When we make a LegacySystemConfig contract for Tithan,  we must set all the corresponding address information. 
   
_type == 2 only means the Optimism bedrock with the native TON. At this time, l2TON is LEGACY_ERC20_NATIVE_TOKEN (0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000). (Thanos is this type.)

I think it will be easier to understand if you check the test script as well.
https://github.com/tokamak-network/ton-staking-v2/tree/codeReview?tab=readme-ov-file#test
