### ISSUE TITLE
no type safety on ```target``` and ```value``` parameters in ```_call``` function

### ISSUE THREAD

**Issue by mehdi-defiesta** [tokamak-network/ton-staking-v2#19]
**Describe the bug**
There is no type safety on data and target parameters in ```call``` function in OperatorV1_1.sol. Any operator is able to send the entire balance of the contract to address(0) (or any non existing address) leading to funds loss. Operator could send funds to their EOA address as well.

code snippet:
```Solidity
    // @audit no type safety on data parameter => vulnerabilities if the input is not properly validated
    function _call(address target, uint256 value, bytes memory data) internal {
        (bool success, bytes memory result) = target.call{value : value}(data);
        if (!success) {
            assembly {
                revert(add(result, 32), mload(result))
            }
        }
    }
```

**Configuration**
- Severity: Low 

**Impact**
Any operator is able to send the entire balance of the contract to address(0) (or any non existing address) leading to funds loss. Operator could send funds to their EOA address as well.

**Recommendation**
We must add an address(0) safety check and implement an ```ìsContract``` function in order to avoid sending ETH to the wrong target. Moreover, It seems important to add a gas parameter to the call function in the case a sequencing function is abnormally gas consuming. 

```Solidity
function _call(address target, uint256 value, bytes memory data) internal {
        require(target != address(0), "Target address cannot be zero");
        require(isContract(target), "Target must be a contract");

        (bool success, bytes memory result) = target.call{value: value, gas: 5000}(data);
        if (!success) {
            // Bubble up the revert reason
            if (result.length > 0) {
                assembly {
                    let returndata_size := mload(result)
                    revert(add(32, result), returndata_size)
                }
            } else {
                revert("Call failed without a revert reason");
            }
        }

        emit CallResult(success, result);
    }

    function isContract(address account) internal view returns (bool) {
        uint256 size;
        assembly {
            size := extcodesize(account)
        }
        return size > 0;
    }
```

**Comment by mehdi-defiesta** [comment]
I agree. I guess we should either remove the execute and executeBatch function or add more safety checks. Severity is Low though because we should assume operators are trusted.

**Comment by Zena-park** [comment]
@mehdi-defiesta I deleted them.

**Comment by Zena-park** [comment]
I'm trying to delete the execute and executeBatch functions. This is because it is a function that does not need to be used in the Operator contract yet. @parth-15 Are you opposed to deleting it?
