### ISSUE TITLE
Add memo field to layer2Candidate & function for change memo about Bridge & explorer address

### ISSUE THREAD

**Issue by cd4761** [tokamak-network/ton-staking-v2#24]
**Is your feature request related to a problem? Please describe.**
<img width="1408" alt="image" src="https://github.com/tokamak-network/ton-staking-v2/assets/8609984/3e003509-d3a4-45c3-999d-30e595d59fcf">

We need information of that field and need to change this value

**Describe alternatives you've considered**
Add changeMemo function for Bridge & Explorer address & add field in event

**Additional context**

**Comment by Zena-park** [comment]
The bridge contract address is in L1 Contract addresses ( on the top right ).
