### ISSUE TITLE
[Question]  Why is there an updateSeigniorageLayer function?

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/ton-staking-v2#31]
**Question**
In the end, it only checks the existence of layer 2 and calls the updateSeigniorage function, but it is strange to have a separate function to check the existence of layer 2.

**Comment by Zena-park** [comment]
This function was added considering user convenience and front-end development convenience.

**Comment by zzooppii** [comment]
i understand it 
thank you for your answer
