### ISSUE TITLE
stakeOfAllLayers() + stakeOfAllLayersAt() if there is a registered layer2 without coinage, return may fail 

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/ton-staking-v2#36]
https://github.com/tokamak-network/ton-staking-v2/blob/2cc9016520e1c08bd41958a764f8af5e3f324d72/contracts/stake/managers/SeigManagerV1_2.sol#L606C1-L620C4

**Comment by Zena-park** [comment]
@suahnkim I fixed it. Please check if it's okay to close the issue.

**Comment by suahnkim** [comment]
checked that it is fixed. closing the issue
