### ISSUE TITLE
Custom Errors

### ISSUE THREAD

**Issue by demis1997** [tokamak-network/ton-staking-v2#45]
**Describe the bug**
Informational/low Bug: You are using require statements throughout the contract, you can opt to use custom errors instead for saving gas. This is likely to come up in an audit

**To Reproduce**
Cannot reproduce,  but can be seen in most of the functions like so:
```
  function onApprove(
    address owner,
    address spender,
    uint256 amount,
    bytes calldata data
  ) external returns (bool) {
    require(msg.sender == _wton, "DepositManager: only accept WTON approve callback");

    address layer2 = _decodeDepositManagerOnApproveData(data);
    require(_deposit(layer2, owner, amount, owner));

    return true;
  }
```

**Expected behavior**
You can replace the require statements with an if statement emitting a custom error if conditons are not met. Please note that the tests will likely have to change too so they do not fail

**Comment by Zena-park** [comment]
Thank you. @demis1997 

But the depositManager are currently deployed on the mainnet and are in service. Therefore, we are trying to patch only bugs in the existing operating functions.

And, we plan to additionally distribute code for upgraded functions related to TON Staking V2.
The contracts to be distributed are as follows. If you request a code change for the contract below, we will review it.
The current test branch is [internal-test-(2024.10)](https://github.com/tokamak-network/ton-staking-v2/tree/internal-test-(2024.10)).

/contracts/layer2/L2RegistryProxy.sol
/contracts/layer2/L2RegistryV1_1.sol
/contracts/layer2/Layer2ManagerProxy.sol
/contracts/layer2/Layer2ManagerV1_1.sol
/contracts/layer2/OperatorProxy.sol
/contracts/layer2/factory/OperatorFactory.sol
/contracts/layer2/OperatorV1_1.sol
/contracts/dao/Layer2CandidateProxy.sol
/contracts/dao/Layer2CandidateV1_1.sol
/contracts/stake/managers/SeigManagerV1_3.sol
/contracts/stake/managers/DepositManagerV1_1.sol
