### ISSUE TITLE
For loop optimisation and potential gas limit reach

### ISSUE THREAD

**Issue by demis1997** [tokamak-network/ton-staking-v2#46]
**Describe the bug**
There are instances such as the one below where you could benefit from caching the array length and using `++i` instead in your `for` loops. I am currently testing to see if this loop in your deposit function can cause the contract to be unusable and lead to a critical vulnerability. Regardless of that, optimising the loop can help mitigate this to some extent too.
```
  function deposit(address layer2, address[] memory accounts, uint256[] memory amounts) external returns (bool) {
    require(accounts.length != 0, 'no account');
    require(accounts.length == amounts.length, 'wrong lenth');

    for (uint256 i = 0; i < accounts.length; i++){
      require(_deposit(layer2, accounts[i], amounts[i], msg.sender));
    }

    return true;
  }

```

**To Reproduce**
You can copy paste the test you are using to deposit funds into the stake contracts via the manager and change it so that it keeps depositing until the gas limit is reached. Alternatively you can cause it to loop over and over and see if the gas costs increment exponentially.
Your staking tests found in **deposit_snapshot.ts**  can include a test which continuously stakes to check the gas cost difference

```
    // Get initial staked amount
    let stakedA = await deployed.seigManagerV2["stakeOf(address,address)"](layer2, account.address);

    // Continuously stake and measure gas consumption
    for (let i = 0; i < iterations; i++) {
        const tx = await deployed.depositManagerV2.connect(account)["deposit(address,uint256)"](
            layer2,
            wtonAmount
        );
        const receipt = await tx.wait(); // Wait for the transaction to be mined

        console.log(`Iteration ${i + 1}: Gas used - ${receipt.gasUsed.toString()}`);
        totalStakedAmount = totalStakedAmount.add(wtonAmount); // Accumulate the total staked amount
    }

    // Get the staked amount after continuous staking
    let stakedB = await deployed.seigManagerV2["stakeOf(address,address)"](layer2, account.address);

    // Ensure that the staked amount increased correctly after all iterations
    expect(roundDown(stakedB.add(ethers.constants.Two), 1)).to.be.eq(
        roundDown(stakedA.add(totalStakedAmount), 1)
    );
```

**Additional context**
I will create another issue after I have tested the vulnerabilit.  This issue was created to optimise gas costs in your loops specifically

**Comment by Zena-park** [comment]
Thank you. @demis1997 
Your opinion is reasonable.

But the SeigManager and the depositManager are currently deployed on the mainnet and are in service. Therefore, we are trying to patch only bugs in the existing operating functions.

And, we plan to additionally distribute code for upgraded functions related to TON Staking V2.
The contracts to be distributed are as follows. If you request a code change for the contract below, we will review it.
The current test branch is [internal-test-(2024.10)](https://github.com/tokamak-network/ton-staking-v2/tree/internal-test-(2024.10)).
-  /contracts/layer2/L2RegistryProxy.sol 
- /contracts/layer2/L2RegistryV1_1.sol 
- /contracts/layer2/Layer2ManagerProxy.sol 
- /contracts/layer2/Layer2ManagerV1_1.sol 
- /contracts/layer2/OperatorProxy.sol 
- /contracts/layer2/factory/OperatorFactory.sol 
- /contracts/layer2/OperatorV1_1.sol 
- /contracts/dao/Layer2CandidateProxy.sol
- /contracts/dao/Layer2CandidateV1_1.sol  
- /contracts/stake/managers/SeigManagerV1_3.sol
- /contracts/stake/managers/DepositManagerV1_1.sol
