### ISSUE TITLE
[internal test - Contract Bugs]: [Suggest] guard upgrade

### ISSUE THREAD

**Issue by DevUreak** [tokamak-network/ton-staking-v2#48]
### Describe the bug

Describe the bug and its behavior! You can reference the problematic code using links (internal-test-(2024.10) branch)

Storing storage uses high gas, Reentrancy-related locking functions perform unnecessary writes. 
This function is available from solidity 0.8.24, and it is easy to convert, so it would be good to consider.

### Impact

The current version of the code is as follows :
```
    // Layer2ManagerStorage.sol
    modifier ifFree {
        require(!_lock, "lock");
        _lock = true;
        _;
        _lock = false;
    }
```

I've previously written code specs like this (It can be of similar code spec) : 
```
modifier guard() {
 assembly ("memory-safe"){
      if tload(0){
         revert(0,0)  
     }
     tstore(0,1)
 }
 __;
 assembly ("memory-safe"){
    tstore(0,0)
 }
}


```

### Recommendation

contracts/layer2/Layer2ManagerStorage.sol

**Comment by Zena-park** [comment]
Thank you. @DevUreak 
During the hardhat test,
an error occurred when using tstore, and the test did not work properly.
If the test is successful, please send me the code and I will check it.

https://github.com/tokamak-network/ton-staking-v2/blob/79f17dee8e7f0d628f6f4479db1c03a0930e6fb0/contracts/layer2/Layer2ManagerV1_1.sol#L249-L263

![스크린샷 2024-10-15 오전 12 24 40](https://github.com/user-attachments/assets/93827151-50f2-4a8b-b236-c92e4dfc00c8)
![스크린샷 2024-10-15 오전 12 24 58](https://github.com/user-attachments/assets/47225d12-1d8e-45c2-aff2-18ceeda0be0c)

**Comment by DevUreak** [comment]
I will fix it and let you know. thanks

**Comment by Zena-park** [comment]
@DevUreak Thank you.
The above tests were run on the[ test-#48 branch](https://github.com/tokamak-network/ton-staking-v2/tree/test-%2348).

**Comment by DevUreak** [comment]
An error occurred during testing in the [test-#48](https://github.com/tokamak-network/ton-staking-v2/tree/test-%2348) branch. It worked normally in Remix, but there seems to be a problem in the hardhat environment. There is no problem with tload(), but there seems to be a problem with tstore. @Zena-park

**Comment by Zena-park** [comment]
It hasn't been tested well and we don't have experience using it on mainnet yet, so we won't implement it this time. 
Thank you. @DevUreak
