### ISSUE TITLE
renounceOwnership() can DoS the contract if used by the owner

### ISSUE THREAD

**Issue by mehdi-defiesta** [tokamak-network/ton-staking-v2#50]
### Describe the bug

I think this [function](https://github.com/tokamak-network/ton-staking-v2/blob/9a171c2652afbfa58e85eba3a3a4374fef2391df/contracts/common/AuthControlCoinage.sol#L67) in AuthControlSeigManager and AuthControlCoinage contracts must be depreciated:
```Solidity
function renounceOwnership() public onlyOwner {
    renounceRole(DEFAULT_ADMIN_ROLE, msg.sender);
}
```

### Impact

If the owner wrongly use this function, it would DoS the contract as many functions using onlyOwner modifier would not be usable. 

### Recommendation

keep and use `transferOwnership `instead

**Comment by mehdi-defiesta** [comment]
@zzooppii yes it's true that onlyOwner functions won't be used. Therefore, all the setRate functions, setDelay functions and minimum amount functions  (from the SeigManager) won't be accessible anymore. Moreover, if the owner calls renounceOwnership, it will not be possible to attribute the ownership to another address.

**Comment by zzooppii** [comment]
@mehdi-defiesta 
Yes, creating a contract that no longer has an owner is what we intended. 😄
