### ISSUE TITLE
[internal test - Contract Bugs]: Registrant Authority Management

### ISSUE THREAD

**Issue by DevUreak** [tokamak-network/ton-staking-v2#51]
### Describe the bug

Describe the bug and its behavior! You can reference the problematic code using links (internal-test-(2024.10) branch)

Registrant rights are managed by the L1BridgeRegistry contract. Our current policy is to grant "REGISTRANT_ROLE" to the EOA of the server that actually deploys L2 when opening on-demand-L2.

I think there might be a slight problem with the code below.

The code below:
```
  function changeType(address rollupConfig, uint8 _type, address _l2TON, string calldata _name)  external  onlyRegistrant {

        ROLLUP_INFO memory info = rollupInfo[rollupConfig];
        if (info.rollupType == 0) revert ChangeError(1);
        if (info.rollupType == _type) revert ChangeError(2);
        if (_l2TON == address(0)) revert ChangeError(3);
        if (bytes(_name).length == 0) revert ChangeError(4);

        _resetRollupConfig(rollupConfig) ;
        _registerRollupConfig(rollupConfig, _type, _l2TON, _name);

        emit ChangedType(rollupConfig, _type, _l2TON, _name);
    }


```

For example

There is a chain that has stopped paying seigniorage, but another wallet with Registrant rights can invalidate this by calling the changeType() function.

The invalidating code is as follows:

```
    function _resetRollupConfig(address rollupConfig) internal {
        ROLLUP_INFO storage info = rollupInfo[rollupConfig];
        if(info.rejectedSeigs) revert NonRejectedError();

        address l1Bridge_ = IOptimismSystemConfig(rollupConfig).l1StandardBridge();
        address optimismPortal_ = IOptimismSystemConfig(rollupConfig).optimismPortal();

        if (l1Bridge_ != address(0) && l1Bridge[l1Bridge_]) l1Bridge[l1Bridge_] = false;
        if (optimismPortal_ != address(0) && portal[optimismPortal_]) portal[optimismPortal_] = false;

        registeredNames[bytes32(bytes(info.name))] = false;

        info.rollupType = 0;
        info.l2TON = address(0);
        info.rejectedSeigs = false;
        info.rejectedL2Deposit = false;
        info.name = '';
    }




```

### Recommendation

layer2/L1BridgeRegistryV1_1.sol

**Comment by Zena-park** [comment]
@DevUreak Thank you for Checking.

Since there is a condition in the _resetRollupConfig function 
https://github.com/tokamak-network/ton-staking-v2/blob/37bac22659d03ac9e50455da3412ccf3ab5a6810/contracts/layer2/L1BridgeRegistryV1_1.sol#L437

If the seigniorage payment is stopped (info.rejectedSeigs == true), the changeType function execution fails.

**Comment by DevUreak** [comment]
Ah, I will write more carefully, but isn't it possible to call other wallets other than the example that have been granted Registrant ROLE? It seems that the address is not being treated as an exception. @Zena-park

**Comment by Zena-park** [comment]
Do you have a scenario you would like to test?

Let me know and I will add your desired test cases to [the basic test script](https://github.com/tokamak-network/ton-staking-v2/blob/37bac22659d03ac9e50455da3412ccf3ab5a6810/test/layer2/units/0.L1BridgeRegistry.test.ts#L236-L250). 
Feel free to tell me.

**Comment by DevUreak** [comment]
We discussed the issue.  However, the decision appears to vary depending on internal policy. However, I still think this issue is risky from an operational perspective. issue is closed @Zena-park
