### ISSUE TITLE
Minor suggestion - Implementations of the setFactor() function can be put in require statements

### ISSUE THREAD

**Issue by avishkarabhishek786** [tokamak-network/ton-staking-v2#56]
**Describe the bug**
Minor suggestion - Since setFactor() function returns bool it can be utilised to check if the function ran successfully. 

**To Reproduce**
The setFactor() function can be found in `contracts/stake/tokens/AutoRefactorCoinage.sol` file and its function signature is as follows: 

`function setFactor(uint256 factor_) external onlyOwner returns (bool)`

One of the many places it is being used is in _updateSeigniorage() function in the [contracts/stake/managers/SeigManagerV1_3.sol ](https://github.com/tokamak-network/ton-staking-v2/blob/37bac22659d03ac9e50455da3412ccf3ab5a6810/contracts/stake/managers/SeigManagerV1_3.sol#L421)file as follows:

`coinage.setFactor(
      _calcNewFactor(
        prevTotalSupply,
        nextTotalSupply,
        coinage.factor()
      )
    );`

Since the setFactor function returns bool we could optionally check if it was successful. 

**Expected behavior**

The line above can be refactored to:

`require(coinage.setFactor(
      _calcNewFactor(
        prevTotalSupply,
        nextTotalSupply,
        coinage.factor()
      )
), 'some message');`

**Comment by Zena-park** [comment]
@avishkarabhishek786  Thank you.
I reflected on it.  620d853d400600d8a85792bb7a20be8d6f6f8398
